//! Canonicalize pass.
//!
//! Normalizes SIR into a canonical form: eliminating redundancies,
//! and standardizing naming.
//!
//! Implemented transformations:
//! - Identity elimination: removes SirOp::Identity nodes that are pure
//!   pass-throughs (e.g., TracedOp::Output wrapper, TracedOp::GetItem
//!   structural selection) by rewiring their consumers to use the
//!   identity's input directly. Graph input placeholders (Identity with
//!   input="__placeholder__") are preserved since they define the graph
//!   input signature.

use ane_ir::sir::{SirGraph, SirNode, SirNodeId, SirOp};
use anyhow::Result;
use std::collections::HashMap;

/// Canonicalize pass implementation.
pub struct CanonicalizePass {}

impl Default for CanonicalizePass {
    fn default() -> Self {
        Self::new()
    }
}

impl CanonicalizePass {
    pub fn new() -> Self {
        Self {}
    }

    /// Run the canonicalize pass.
    ///
    /// Currently implements:
    /// - Identity elimination: removes pass-through Identity ops
    ///
    /// Future work will include:
    /// - Common subexpression elimination
    /// - Dead code elimination
    /// - Fuse linear + bias into a single LinearProjection op
    /// - Standardize node naming conventions
    /// - Merge consecutive elementwise operations
    pub fn run(&self, input: SirGraph) -> Result<SirGraph> {
        Self::eliminate_identities(input)
    }

    /// Eliminate pass-through Identity operations.
    ///
    /// Identity ops are generated by:
    /// - `TracedOp::Output`: wraps the final graph output in an identity
    /// - `TracedOp::GetItem`: structural selection emitted as identity
    /// - `TracedOp::Identity`: PyTorch `.contiguous()`, `.size()`, etc.
    ///
    /// These are pure pass-throughs that add no computational value.
    /// We eliminate them by creating a substitution map: for each identity
    /// node, map its output ID → its input ID. Then we rewire all
    /// node references using this map.
    ///
    /// Graph input placeholders (Identity with input="__placeholder__") are
    /// preserved because they define the graph's input signature.
    fn eliminate_identities(graph: SirGraph) -> Result<SirGraph> {
        let graph_input_ids: std::collections::HashSet<&SirNodeId> = graph.inputs.iter().collect();

        let mut subst: HashMap<SirNodeId, SirNodeId> = HashMap::new();

        for node in &graph.nodes {
            if let SirOp::Identity { input } = &node.op {
                // Preserve graph input placeholders.
                // NOTE (M-018): The "__placeholder__" sentinel marks graph input
                // signature nodes. This is a structural convention (not a model-specific
                // heuristic) — all SIR builders use this sentinel for input placeholders.
                if input.0 == "__placeholder__" {
                    continue;
                }
                // Preserve nodes that are graph inputs themselves
                if graph_input_ids.contains(&node.id) {
                    continue;
                }
                subst.insert(node.id.clone(), input.clone());
            }
        }

        // Transitively resolve substitution chains (M-025: hard error on cycles)
        let subst = Self::resolve_subst_chain(&subst)?;

        if subst.is_empty() {
            return Ok(graph);
        }

        // Apply substitutions to all node operands and graph outputs.
        let nodes: Vec<SirNode> = graph
            .nodes
            .into_iter()
            .filter(|node| !subst.contains_key(&node.id))
            .map(|mut node| {
                node.op = Self::rewrite_op_refs(&node.op, &subst);
                node
            })
            .collect();

        let outputs: Vec<SirNodeId> =
            graph.outputs.into_iter().map(|id| Self::resolve_id(&id, &subst)).collect();

        Ok(SirGraph { nodes, inputs: graph.inputs, outputs })
    }

    /// Transitively resolve substitution chains.
    ///
    /// If A → B and B → C, this resolves A → C directly so that we
    /// don't need to apply substitutions iteratively.
    fn resolve_subst_chain(
        subst: &HashMap<SirNodeId, SirNodeId>,
    ) -> Result<HashMap<SirNodeId, SirNodeId>> {
        let mut resolved = HashMap::new();
        for (key, target) in subst {
            let mut final_target = target.clone();
            let mut steps = 0;
            while let Some(next) = subst.get(&final_target) {
                final_target = next.clone();
                steps += 1;
                if steps > 100 {
                    // M-025: Circular substitution chain is a hard error.
                    // Previously this logged a warning and returned the
                    // partially-resolved target, which could silently produce
                    // incorrect graph references. Now we return an error so
                    // the caller knows the graph has a circular substitution.
                    anyhow::bail!(
                        "CanonicalizePass: substitution chain resolution hit 100-step limit \
                         for key {:?} → target {:?}. This indicates a circular substitution \
                         chain in the SIR graph that must be fixed before canonicalization.",
                        key,
                        final_target
                    );
                }
            }
            resolved.insert(key.clone(), final_target);
        }
        Ok(resolved)
    }

    /// Rewrite all SirNodeId references in a SirOp using the substitution map.
    fn rewrite_op_refs(op: &SirOp, subst: &HashMap<SirNodeId, SirNodeId>) -> SirOp {
        macro_rules! r {
            ($id:expr) => {
                Self::resolve_id($id, subst)
            };
        }

        match op {
            SirOp::Identity { input } => SirOp::Identity { input: r!(input) },
            SirOp::LinearProjection { input, weight, bias } => SirOp::LinearProjection {
                input: r!(input),
                weight: weight.clone(),
                bias: bias.clone(),
            },
            SirOp::RMSNorm { input, weight, epsilon, axes } => SirOp::RMSNorm {
                input: r!(input),
                weight: weight.clone(),
                epsilon: *epsilon,
                axes: axes.clone(),
            },
            SirOp::RoPETransform { input, tables } => {
                SirOp::RoPETransform { input: r!(input), tables: tables.clone() }
            }
            SirOp::ScaledDotProductAttention { query, key, value, attention_mask, scale } => {
                SirOp::ScaledDotProductAttention {
                    query: r!(query),
                    key: r!(key),
                    value: r!(value),
                    attention_mask: attention_mask.as_ref().map(|m| r!(m)),
                    scale: *scale,
                }
            }
            SirOp::AttentionBlock { q, k, v, mask, rope } => SirOp::AttentionBlock {
                q: r!(q),
                k: r!(k),
                v: r!(v),
                mask: mask.as_ref().map(|m| r!(m)),
                rope: rope.as_ref().map(|m| r!(m)),
            },
            SirOp::Add { x, y } => SirOp::Add { x: r!(x), y: r!(y) },
            SirOp::Mul { x, y } => SirOp::Mul { x: r!(x), y: r!(y) },
            SirOp::MatMul { a, b } => SirOp::MatMul { a: r!(a), b: r!(b) },
            SirOp::RealDiv { x, y } => SirOp::RealDiv { x: r!(x), y: r!(y) },
            SirOp::Gather { input, indices, axis } => {
                SirOp::Gather { input: r!(input), indices: r!(indices), axis: *axis }
            }
            SirOp::Reshape { input, target_shape } => {
                SirOp::Reshape { input: r!(input), target_shape: target_shape.clone() }
            }
            SirOp::Transpose { input, perm } => {
                SirOp::Transpose { input: r!(input), perm: perm.clone() }
            }
            SirOp::Tile { input, reps } => SirOp::Tile { input: r!(input), reps: reps.clone() },
            SirOp::ReduceMean { input, axes, keep_dims } => {
                SirOp::ReduceMean { input: r!(input), axes: axes.clone(), keep_dims: *keep_dims }
            }
            SirOp::ReduceSum { input, axes, keep_dims } => {
                SirOp::ReduceSum { input: r!(input), axes: axes.clone(), keep_dims: *keep_dims }
            }
            SirOp::Rsqrt { input } => SirOp::Rsqrt { input: r!(input) },
            SirOp::Sqrt { input } => SirOp::Sqrt { input: r!(input) },
            SirOp::Softmax { input, axis } => SirOp::Softmax { input: r!(input), axis: *axis },
            SirOp::Silu { input } => SirOp::Silu { input: r!(input) },
            SirOp::Relu { input } => SirOp::Relu { input: r!(input) },
            SirOp::Gelu { input, mode } => SirOp::Gelu { input: r!(input), mode: mode.clone() },
            SirOp::Sigmoid { input } => SirOp::Sigmoid { input: r!(input) },
            SirOp::Tanh { input } => SirOp::Tanh { input: r!(input) },
            SirOp::Exp { input } => SirOp::Exp { input: r!(input) },
            SirOp::Log { input, epsilon } => SirOp::Log { input: r!(input), epsilon: *epsilon },
            SirOp::Cos { input } => SirOp::Cos { input: r!(input) },
            SirOp::Sin { input } => SirOp::Sin { input: r!(input) },
            SirOp::Abs { input } => SirOp::Abs { input: r!(input) },
            SirOp::Neg { input } => SirOp::Neg { input: r!(input) },
            SirOp::Topk { input, k, axis } => SirOp::Topk { input: r!(input), k: *k, axis: *axis },
            SirOp::SliceByIndex {
                input,
                begin,
                end,
                stride,
                begin_mask,
                end_mask,
                squeeze_mask,
            } => SirOp::SliceByIndex {
                input: r!(input),
                begin: begin.clone(),
                end: end.clone(),
                stride: stride.clone(),
                begin_mask: begin_mask.clone(),
                end_mask: end_mask.clone(),
                squeeze_mask: squeeze_mask.clone(),
            },
            SirOp::ExpandDims { input, axis } => {
                SirOp::ExpandDims { input: r!(input), axis: axis.clone() }
            }
            SirOp::Squeeze { input, axis } => {
                SirOp::Squeeze { input: r!(input), axis: axis.clone() }
            }
            SirOp::Concat { inputs, axis } => {
                SirOp::Concat { inputs: inputs.iter().map(|id| r!(id)).collect(), axis: *axis }
            }
            SirOp::Pad { input, pad_amounts, mode, constant_value } => SirOp::Pad {
                input: r!(input),
                pad_amounts: pad_amounts.clone(),
                mode: mode.clone(),
                constant_value: *constant_value,
            },
            SirOp::Where { condition, x, y } => {
                SirOp::Where { condition: r!(condition), x: r!(x), y: r!(y) }
            }
            SirOp::Fill { shape, value, dtype } => {
                SirOp::Fill { shape: shape.clone(), value: *value, dtype: dtype.clone() }
            }
            SirOp::FillLike { ref_tensor, value, dtype } => {
                SirOp::FillLike { ref_tensor: r!(ref_tensor), value: *value, dtype: dtype.clone() }
            }
            SirOp::Sampler {
                logits,
                temperature,
                top_p,
                rep_penalty,
                min_p,
                top_k,
                gumbel_noise,
            } => SirOp::Sampler {
                logits: r!(logits),
                temperature: *temperature,
                top_p: *top_p,
                rep_penalty: *rep_penalty,
                min_p: *min_p,
                top_k: *top_k,
                gumbel_noise: *gumbel_noise,
            },
            SirOp::StateRead { state_id, offset, shape } => SirOp::StateRead {
                state_id: state_id.clone(),
                offset: *offset,
                shape: shape.clone(),
            },
            SirOp::StateWrite { state_id, offset, value } => {
                SirOp::StateWrite { state_id: state_id.clone(), offset: *offset, value: r!(value) }
            }
            SirOp::Const { .. }
            | SirOp::OneHot { .. }
            | SirOp::Conv { .. }
            | SirOp::Einsum { .. }
            | SirOp::DecodeStep { .. }
            | SirOp::SliceBySize { .. }
            | SirOp::SlidingWindows { .. }
            | SirOp::GatherAlongAxis { .. }
            | SirOp::GatherNd { .. }
            | SirOp::Quantize { .. }
            | SirOp::Dequantize { .. }
            | SirOp::LayerNorm { .. }
            | SirOp::BatchNorm { .. }
            | SirOp::Softplus { .. }
            | SirOp::Softsign { .. }
            | SirOp::Threshold { .. }
            | SirOp::Clip { .. }
            | SirOp::Prelu { .. }
            | SirOp::Split { .. }
            | SirOp::Stack { .. }
            | SirOp::SpaceToBatch { .. }
            | SirOp::BatchToSpace { .. } => op.clone(),
            // Fallthrough: ops without SirNodeId inputs, or rare ops
            // that we don't expect in identity-elimination paths
            _ => op.clone(),
        }
    }

    /// Resolve a single SirNodeId through the substitution map.
    fn resolve_id(id: &SirNodeId, subst: &HashMap<SirNodeId, SirNodeId>) -> SirNodeId {
        subst.get(id).cloned().unwrap_or_else(|| id.clone())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ane_ir::sir::{SirMetadata, SirNode, SirNodeId, SirOp, SirTargetAnnotation, TaskOrigin};

    fn make_node(id: &str, op: SirOp) -> SirNode {
        SirNode {
            id: SirNodeId(id.to_string()),
            op,
            name: id.to_string(),
            metadata: SirMetadata {
                task_origin: TaskOrigin::Synthetic,
                model_id: None,
                quality_contract: None,
                precision_override: None,
            },
            target_annotation: SirTargetAnnotation::default(),
        }
    }

    #[test]
    fn test_eliminate_trailing_identity() {
        let graph = SirGraph {
            nodes: vec![
                make_node(
                    "input",
                    SirOp::Identity { input: SirNodeId("__placeholder__".to_string()) },
                ),
                make_node(
                    "linear",
                    SirOp::LinearProjection {
                        input: SirNodeId("input".to_string()),
                        weight: "w".to_string(),
                        bias: None,
                    },
                ),
                make_node("output", SirOp::Identity { input: SirNodeId("linear".to_string()) }),
            ],
            inputs: vec![SirNodeId("input".to_string())],
            outputs: vec![SirNodeId("output".to_string())],
        };

        let pass = CanonicalizePass::new();
        let result = pass.run(graph).unwrap();

        assert!(!result.nodes.iter().any(|n| n.id.0 == "output"));
        assert_eq!(result.outputs, vec![SirNodeId("linear".to_string())]);
        assert!(result.nodes.iter().any(|n| n.id.0 == "input"));
    }

    #[test]
    fn test_preserve_placeholder_identity() {
        let graph = SirGraph {
            nodes: vec![make_node(
                "input_ids",
                SirOp::Identity { input: SirNodeId("__placeholder__".to_string()) },
            )],
            inputs: vec![SirNodeId("input_ids".to_string())],
            outputs: vec![SirNodeId("input_ids".to_string())],
        };

        let pass = CanonicalizePass::new();
        let result = pass.run(graph).unwrap();

        assert_eq!(result.nodes.len(), 1);
        assert_eq!(result.outputs, vec![SirNodeId("input_ids".to_string())]);
    }

    #[test]
    fn test_identity_chain_resolution() {
        let graph = SirGraph {
            nodes: vec![
                make_node("a", SirOp::Identity { input: SirNodeId("__placeholder__".to_string()) }),
                make_node("b", SirOp::Identity { input: SirNodeId("a".to_string()) }),
                make_node("c", SirOp::Identity { input: SirNodeId("b".to_string()) }),
                make_node(
                    "d",
                    SirOp::LinearProjection {
                        input: SirNodeId("c".to_string()),
                        weight: "w".to_string(),
                        bias: None,
                    },
                ),
            ],
            inputs: vec![SirNodeId("a".to_string())],
            outputs: vec![SirNodeId("d".to_string())],
        };

        let pass = CanonicalizePass::new();
        let result = pass.run(graph).unwrap();

        assert!(!result.nodes.iter().any(|n| n.id.0 == "b"));
        assert!(!result.nodes.iter().any(|n| n.id.0 == "c"));

        let d_node = result.nodes.iter().find(|n| n.id.0 == "d").unwrap();
        if let SirOp::LinearProjection { input, .. } = &d_node.op {
            assert_eq!(input.0, "a");
        } else {
            panic!("Expected LinearProjection");
        }
    }

    // M-025: Circular substitution chain must return a hard error.
    // A→B→C→A creates a cycle. The resolve_subst_chain() method detects
    // the cycle and returns an error rather than silently producing an
    // incorrect result.
    #[test]
    fn test_m025_circular_substitution_chain_returns_error() {
        // Build a circular chain of Identity nodes: a→b, b→c, c→a
        // This creates a cycle in the substitution map that resolve_subst_chain
        // must detect and report as a hard error.
        let graph = SirGraph {
            nodes: vec![
                make_node(
                    "input",
                    SirOp::Identity { input: SirNodeId("__placeholder__".to_string()) },
                ),
                // Circular identities: each points to the next, wrapping around
                make_node("a", SirOp::Identity { input: SirNodeId("b".to_string()) }),
                make_node("b", SirOp::Identity { input: SirNodeId("c".to_string()) }),
                make_node("c", SirOp::Identity { input: SirNodeId("a".to_string()) }),
            ],
            inputs: vec![SirNodeId("input".to_string())],
            outputs: vec![SirNodeId("input".to_string())],
        };

        let pass = CanonicalizePass::new();
        // M-025: Circular chains must return an error, not silently succeed
        let result = pass.run(graph);
        assert!(result.is_err(), "M-025: Circular substitution chain must return a hard error");
        let err_msg = result.unwrap_err().to_string();
        assert!(
            err_msg.contains("circular substitution"),
            "Error message should mention circular substitution, got: {}",
            err_msg
        );
    }
}
