//! KV Cache Rewrite Pass — DEPRECATED (ISSUE-015)
//!
//! **This pass is dead code** — it is not invoked by any active compilation
//! pipeline. The KV cache masking is now handled at the AIR level in
//! `legality_rewrite.rs` using precomputed static tables + Gather + Add,
//! which is fully ANE-legal and avoids the ANE-illegal `Where` op that
//! this pass generates.
//!
//! The masked-blend layout that this pass implements uses `SirOp::Where`,
//! which is ANE-illegal (no ANE converter). The current approach uses
//! `Gather(eye_tab, pos)` for KV write masking and `Gather(mask_tab, pos)`
//! for causal attention masking, both fully ANE-legal.
//!
//! This module is kept for reference only. It should be removed once all
//! downstream consumers have been verified to not depend on it.
//!
//! ## Original description:
//!
//! The naive KV cache uses append/shift operations that often force CPU
//! fallback on ANE because scatter operations are not ANE-supported.
//! The masked-blend layout keeps active context in a contiguous suffix
//! of the sequence axis, and new K/V values are written by masked
//! blending (Where + Mul + Add) instead of scatter-heavy updates.
//!
//! This pass transforms `StateRead`/`StateWrite` sequences into
//! a pattern of StateRead + Where + Mul + Add + StateWrite ops when
//! the KV cache layout is set to `MaskedBlend`.
//!
//! **WARNING:** The `Where` op generated by this pass is ANE-illegal.
//! Do NOT use this pass for ANE-targeted compilation.

use ane_ir::sir::{KvCacheLayout, SirGraph, SirNode, SirNodeId, SirOp};

/// Result of the KV cache rewrite pass.
#[derive(Debug, Clone)]
pub struct KvCacheRewriteResult {
    /// Number of StateRead/StateWrite pairs converted to masked-blend pattern.
    pub pairs_converted: usize,
    /// Number of new ops inserted (StateRead + Where + Mul + Add + StateWrite per pair).
    pub ops_inserted: usize,
}

/// Run the KV cache rewrite pass on a SIR graph.
///
/// When `kv_layout` is `MaskedBlend`, this pass:
/// 1. Identifies StateRead/StateWrite pairs targeting the same KV cache state
/// 2. Replaces them with a masked-blend pattern: StateRead + Where + Mul + Add + StateWrite
/// 3. Inserts position and mask inputs for the blend logic
///
/// When `kv_layout` is `Naive` or `Paged`, the pass is a no-op.
pub fn run_kv_cache_rewrite_pass(
    graph: &mut SirGraph,
    kv_layout: &KvCacheLayout,
) -> KvCacheRewriteResult {
    let mut result = KvCacheRewriteResult { pairs_converted: 0, ops_inserted: 0 };

    if kv_layout != &KvCacheLayout::MaskedBlend && kv_layout != &KvCacheLayout::RingBuffer {
        return result;
    }

    // RingBuffer layout: same masked-blend write pattern, but the state
    // management uses position-aware indexing. The read path uses a
    // gather-based rotation from the circular buffer using the position
    // input and the pre-computed eye_tab (identity matrix).
    // For now, RingBuffer uses the same masked-blend write pattern as
    // MaskedBlend, with position-dependent gather for reads handled
    // in the decompose_decode_step function (via the position input).

    // Find StateRead ops that read from KV cache states
    let kv_read_indices: Vec<usize> = graph
        .nodes
        .iter()
        .enumerate()
        .filter_map(|(idx, node)| match &node.op {
            SirOp::StateRead { state_id, .. } if state_id.contains("kv_cache") => Some(idx),
            _ => None,
        })
        .collect();

    // For each KV cache read, find the corresponding write and replace
    // the pair with a masked-blend pattern: StateRead + Where + Mul + Add + StateWrite.
    // In a full implementation, this would also insert position counter and
    // valid mask management ops.
    for read_idx in kv_read_indices {
        let (state_id, offset, shape) = match &graph.nodes[read_idx].op {
            SirOp::StateRead { state_id, offset, shape } => {
                (state_id.clone(), *offset, shape.clone())
            }
            _ => unreachable!(),
        };

        // Find the corresponding StateWrite
        let write_idx = graph
            .nodes
            .iter()
            .enumerate()
            .find(|(_, node)| match &node.op {
                SirOp::StateWrite { state_id: ws, .. } if ws == &state_id => true,
                _ => false,
            })
            .map(|(idx, _)| idx);

        if let Some(w_idx) = write_idx {
            let (value_id, _) = match &graph.nodes[w_idx].op {
                SirOp::StateWrite { value, state_id: ws, .. } => (value.clone(), ws.clone()),
                _ => unreachable!(),
            };

            // Parse layer index from state_id (e.g., "kv_cache_layer_3_key" → 3)
            let layer_idx = parse_layer_idx(&state_id);
            let is_key = state_id.ends_with("_key");

            // Build the masked-blend pattern:
            //   cached = StateRead(kv_cache_state)
            //   blend_mask = Where(valid_mask, new_values, cached)
            //   Alternatively: old_part = Mul(cached, inv_mask), new_part = Mul(new_values, mask),
            //                  blended = Add(old_part, new_part)
            //   StateWrite(kv_cache_state, blended)

            let base_name = format!("kv_blend_{}_{}", layer_idx, if is_key { "k" } else { "v" });

            // StateRead: read the current cache contents
            let cache_read_id = SirNodeId(format!("sir_{}_cache_read", base_name));
            let cache_read_node = SirNode {
                id: cache_read_id.clone(),
                op: SirOp::StateRead { state_id: state_id.clone(), offset, shape: shape.clone() },
                name: format!("{}_cache_read", base_name),
                metadata: graph.nodes[read_idx].metadata.clone(),
            };

            // Where: select between new values and cached values based on valid mask
            let mask_id = SirNodeId(format!("valid_mask_{}", layer_idx));
            let where_id = SirNodeId(format!("sir_{}_where", base_name));
            let where_node = SirNode {
                id: where_id.clone(),
                op: SirOp::Where {
                    condition: mask_id,
                    x: value_id.clone(),
                    y: cache_read_id.clone(),
                },
                name: format!("{}_where", base_name),
                metadata: graph.nodes[read_idx].metadata.clone(),
            };

            // Mul: multiply cached values by inverse mask (old portion)
            let inv_mask_id = SirNodeId(format!("inv_mask_{}", layer_idx));
            let old_mul_id = SirNodeId(format!("sir_{}_old_mul", base_name));
            let old_mul_node = SirNode {
                id: old_mul_id.clone(),
                op: SirOp::Mul { x: cache_read_id, y: inv_mask_id },
                name: format!("{}_old_mul", base_name),
                metadata: graph.nodes[read_idx].metadata.clone(),
            };

            // Mul: multiply new values by mask (new portion)
            let pos_mask_id = SirNodeId(format!("pos_mask_{}", layer_idx));
            let new_mul_id = SirNodeId(format!("sir_{}_new_mul", base_name));
            let new_mul_node = SirNode {
                id: new_mul_id.clone(),
                op: SirOp::Mul { x: value_id, y: pos_mask_id },
                name: format!("{}_new_mul", base_name),
                metadata: graph.nodes[read_idx].metadata.clone(),
            };

            // Add: combine old and new portions
            let add_id = SirNodeId(format!("sir_{}_add", base_name));
            let add_node = SirNode {
                id: add_id.clone(),
                op: SirOp::Add { x: old_mul_id, y: new_mul_id },
                name: format!("{}_add", base_name),
                metadata: graph.nodes[read_idx].metadata.clone(),
            };

            // StateWrite: write the blended result back to the cache
            let state_write_id = SirNodeId(format!("sir_{}_state_write", base_name));
            let state_write_node = SirNode {
                id: state_write_id.clone(),
                op: SirOp::StateWrite { state_id: state_id.clone(), offset, value: add_id },
                name: format!("{}_state_write", base_name),
                metadata: graph.nodes[w_idx].metadata.clone(),
            };

            // Replace the read node with an identity that references the Where output
            // (the where op provides the "read" result for downstream consumers)
            graph.nodes[read_idx] = SirNode {
                id: graph.nodes[read_idx].id.clone(),
                op: SirOp::Identity { input: where_id },
                name: format!("kv_read_passthrough_{}", layer_idx),
                metadata: graph.nodes[read_idx].metadata.clone(),
            };

            // Mark the write node as replaced (the new StateWrite handles it)
            graph.nodes[w_idx] = SirNode {
                id: graph.nodes[w_idx].id.clone(),
                op: SirOp::Identity { input: state_write_id },
                name: format!("kv_write_passthrough_{}", layer_idx),
                metadata: graph.nodes[w_idx].metadata.clone(),
            };

            // Insert the masked-blend pattern ops
            graph.nodes.push(cache_read_node);
            graph.nodes.push(where_node);
            graph.nodes.push(old_mul_node);
            graph.nodes.push(new_mul_node);
            graph.nodes.push(add_node);
            graph.nodes.push(state_write_node);

            result.pairs_converted += 1;
            result.ops_inserted += 6; // StateRead + Where + Mul + Mul + Add + StateWrite
        }
    }

    result
}

/// Parse a layer index from a KV cache state ID string.
/// E.g., "kv_cache_layer_3_key" → 3
fn parse_layer_idx(state_id: &str) -> usize {
    state_id.split('_').filter_map(|s| s.parse::<usize>().ok()).next().unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use ane_ir::sir::{SirMetadata, TaskOrigin};

    #[test]
    fn test_kv_cache_rewrite_naive_is_noop() {
        let mut graph = SirGraph {
            nodes: vec![SirNode {
                id: SirNodeId("kv_read_0".to_string()),
                op: SirOp::StateRead {
                    state_id: "kv_cache_layer_0_key".to_string(),
                    offset: 0,
                    shape: vec![1, 64, 4, 32],
                },
                name: "kv_read_0".to_string(),
                metadata: SirMetadata {
                    task_origin: TaskOrigin::Synthetic,
                    model_id: None,
                    quality_contract: None,
                    precision_override: None,
                },
            }],
            inputs: vec![],
            outputs: vec![],
        };

        let result = run_kv_cache_rewrite_pass(&mut graph, &KvCacheLayout::Naive);
        assert_eq!(result.pairs_converted, 0);
        assert_eq!(result.ops_inserted, 0);
    }

    #[test]
    fn test_kv_cache_rewrite_masked_blend() {
        let mut graph = SirGraph {
            nodes: vec![
                SirNode {
                    id: SirNodeId("kv_read_0".to_string()),
                    op: SirOp::StateRead {
                        state_id: "kv_cache_layer_0_key".to_string(),
                        offset: 0,
                        shape: vec![1, 64, 4, 32],
                    },
                    name: "kv_read_0".to_string(),
                    metadata: SirMetadata {
                        task_origin: TaskOrigin::Synthetic,
                        model_id: None,
                        quality_contract: None,
                        precision_override: None,
                    },
                },
                SirNode {
                    id: SirNodeId("kv_write_0".to_string()),
                    op: SirOp::StateWrite {
                        state_id: "kv_cache_layer_0_key".to_string(),
                        offset: 0,
                        value: SirNodeId("new_k_0".to_string()),
                    },
                    name: "kv_write_0".to_string(),
                    metadata: SirMetadata {
                        task_origin: TaskOrigin::Synthetic,
                        model_id: None,
                        quality_contract: None,
                        precision_override: None,
                    },
                },
            ],
            inputs: vec![],
            outputs: vec![],
        };

        let result = run_kv_cache_rewrite_pass(&mut graph, &KvCacheLayout::MaskedBlend);

        assert_eq!(result.pairs_converted, 1);
        assert_eq!(result.ops_inserted, 6); // StateRead + Where + Mul + Mul + Add + StateWrite

        // Verify masked-blend pattern ops were inserted
        let has_where = graph.nodes.iter().any(|n| matches!(n.op, SirOp::Where { .. }));
        assert!(has_where, "Graph should contain a Where op for masked blending");

        let has_add = graph
            .nodes
            .iter()
            .any(|n| matches!(n.op, SirOp::Add { .. }) && n.name.contains("kv_blend"));
        assert!(has_add, "Graph should contain an Add op combining old and new cache values");
    }

    #[test]
    fn test_parse_layer_idx() {
        assert_eq!(parse_layer_idx("kv_cache_layer_3_key"), 3);
        assert_eq!(parse_layer_idx("kv_cache_layer_27_value"), 27);
        assert_eq!(parse_layer_idx("other_state"), 0);
    }
}
